version: '3.3'
services:  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - node-network
  node:
    build:
      context: node    
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: bash -c 'npm start'
    container_name: node    
    ports:
      - "8080:8080"
    networks:
      - node-network
    depends_on:
      - db
networks:
  node-network:
    driver: bridge 


